[package]
name = "streak"
version = "0.1.0"
authors = ["Lancelot Carlson <lcarlson@healpay.com>"]

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_url_params = "0.1"
log = "0.4"
